### PR TITLE
Port to GNOME 45

### LINKED ISSUE #100: Support for G45 version
Hi, could you update the G45 version?
This tutorial might help:

 Here's the official link. https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

PS: Here it's a link to an extension that's already working on G45 https://github.com/ionutbortis/gnome-bedtime-mode/tree/gnome45

### PR DESCRIPTION
**Pull request by DaPigGuy**
Closes #100

### CODE REVIEW

**Comment by qwreey75** [comment]
Anyway, this changes can broken extension in under 45 versions (44)
Maybe need some build script...

**Comment by gilvbp** [comment]
> Anyway, this changes can broken extension in under 45 versions (44) Maybe need some build script...

@qwreey75  Still doesn't work on G45.
image

**Comment by DaPigGuy** [comment]
> Anyway, this changes can broken extension in under 45 versions (44) Maybe need some build script...

Is it really worth the effort to maintain support for only two previous gnome-shell versions?


> > Anyway, this changes can broken extension in under 45 versions (44) Maybe need some build script...
> 
> @DaPigGuy hi there. Still doesn't work on G45.
> 
> image
> 
> Edit: I fixed this problem:
> 
> `gjs[4386]: JS ERROR: RangeError: Provided GType name 'qwreey.quick-settings-tweaks.prefs.notificationsPage' is not valid; automatically sanitized to 'qwreey_quick-settings-tweaks_prefs_notificationsPage' _createGTypeName@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:185:22 registerGObjectType@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:532:41 registerWidgetType@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:92:39 _init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:515:33 _init/Gtk.Widget._classInit@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:75:31 registerClass@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:74:23 @file:///home/gil/.local/share/gnome-shell/extensions/quick-settings-tweaks@qwreey/prefPages/notifications.js:12:40 `
> 
> But it won't work.

I tested on `45.beta`, are you on `45.rc`? I can upgrade later today and test.

**Comment by gilvbp** [comment]
@DaPigGuy ahhh ok, please apologize me. Yes I'm on g45.rc.

**Comment by DaPigGuy** [comment]
@gilvbp Go ahead and try latest changs

**Comment by gilvbp** [comment]
image
@DaPigGuy, great work! All good!

**Comment by qwreey75** [comment]
@DaPigGuy
> Is it really worth the effort to maintain support for only two previous gnome-shell versions?

Yes, many MANY stable distro uses gnome 42~44 for now, such as debian uses gnome 43.6 (currently stable version is 12)
image

Also, many users use gnome previous versions due to instability... should mind it

**Comment by DaPigGuy** [comment]
@qwreey75 Users on older gnome-shell versions can continue to install a compatible version in one click on https://extensions.gnome.org, but if you would like to backport bug fixes and/or features for 43/44, branching off of the current main branch might be a good idea for that

**Comment by DaPigGuy** [comment]
@qwreey75 Could we get this merged and released on e.g.o before the GNOME 45 release next week?

**Comment by DaPigGuy** [comment]
GNOME 45 was released today. An update on extensions.gnome.org would be much appreciated!

**Comment by qwreey75** [comment]
gnome 44 => gnome44-legacy
gnome 45 and up (current) => master

i will test new version is working fine, and update gnome.org. thank you about spend time for this!

**Comment by qwreey75** [comment]
working fine...? i can't test due to busy for college entrance 😢

**Comment by N0ttt** [comment]
> working fine...? i can't test due to busy for college entrance 😢

"redeclaration of const QuickSettingsShutdownMenuBox" fedora 39 pre-release

**Comment by DaPigGuy** [comment]
@qwreey75 @N0ttt I have opened #106 to resolve issues

**Comment by qwreey75** [comment]
image
w..what happen in there? i didn't change Makefile or something

**Comment by DaPigGuy** [comment]
There seems to be an issue with the `po/` directory

**Pull request merged**
